[package]
name = "a-ctor-failed-case"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = { version = "0.2.4", features = ["used_linker"] }
foo = { path = "foo" }

[workspace]
members = [
    "foo",
]
